#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section.
# ──────────────────────────────────────────────────────────────────────────

# Puts the npm publish token into GitHub Actions as the NPM_TOKEN secret on every
# repo that publishes, so a release workflow can publish without anyone's laptop.
# Knobs are overridable from the environment, e.g. REPOS="BotHarness/BotUI".
REPOS="${REPOS:-BotHarness/BotUI BotHarness/BotPixel}"
SECRET_NAME="${SECRET_NAME:-NPM_TOKEN}"
EXPECTED_USER="${EXPECTED_USER:-botharness}"
TOKEN_FILE="${TOKEN_FILE:-$HOME/Documents/code/BotUI/npm_release.token}"
# same patterns as scripts/npm-token.sh: a rejected token vs. no network
REJECTED_PATTERN='401|E401|Unauthorized|ENEEDAUTH|ENOTFOUND|ETIMEDOUT|ENETUNREACH|EAI_AGAIN'

token_is_valid() {
  local candidate="$1" whoami_out
  whoami_out=$(npm whoami --//registry.npmjs.org/:_authToken="$candidate" 2>&1) || true
  printf '%s' "$whoami_out" | grep -qE "$REJECTED_PATTERN" && return 1
  [[ "$whoami_out" == "$EXPECTED_USER" ]]
}

# set_repo_secret REPO VALUE — the value goes in on stdin, never on the command line
set_repo_secret() {
  local repo="$1" value="$2"
  if printf '%s' "$value" | gh secret set "$SECRET_NAME" --repo "$repo" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$repo:$SECRET_NAME")
    printf '  %s✓ set%s %s on %s\n' "$GREEN" "$RESET" "$SECRET_NAME" "$repo"
  else
    SKIPPED+=("$SECRET_NAME on $repo (gh secret set failed — do you have admin on it?)")
    warn "could not set $SECRET_NAME on $repo"
  fi
}

TOTAL_STAGES=4

banner "npm token → GitHub secret"

# ── Stage 1: gh can reach every repo ──────────────────────────────────────
stage "GitHub CLI"
say "Setting a repo secret needs gh, signed in as someone with admin on each repo."
if ! command -v gh >/dev/null 2>&1; then
  warn "gh is not installed."
  note "  brew install gh   then re-run this script"
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  say "gh is installed but not signed in. Signing in now:"
  gh auth login
fi
for repo in $REPOS; do
  if gh repo view "$repo" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$repo"
  else
    warn "gh cannot see $repo with the current account."
    note "  switch accounts with: gh auth switch   (or gh auth login)"
    exit 1
  fi
done
pause "Continue?"

# ── Stage 2: find the token ───────────────────────────────────────────────
stage "The npm token"
say "Reusing the token BotUI's scripts/npm-token.sh already saved, if it still works."
TOKEN=""
if [[ -f "$TOKEN_FILE" ]]; then
  note "found $TOKEN_FILE"
  CANDIDATE=$(tr -d '[:space:]' < "$TOKEN_FILE")
  if [[ -n "$CANDIDATE" ]] && token_is_valid "$CANDIDATE"; then
    say "That token still works as $EXPECTED_USER."
    TOKEN="$CANDIDATE"
  else
    warn "the saved token was rejected — expired, revoked, or from another account."
  fi
else
  note "no token at $TOKEN_FILE (set TOKEN_FILE=... to point elsewhere)"
fi
if [[ -z "$TOKEN" ]]; then
  say ""
  say "Create one here:"
  open_url "https://www.npmjs.com/settings/access-tokens/new"
  step "Packages: scope @botharness (all packages, so new ones like pixel-* can be created)"
  step "Permissions: Read and write"
  step "Tick 'Bypass 2FA' — the account's 2FA is a passkey, which CI cannot answer"
  step "Generate token, then copy it (it is shown only once)"
  say ""
  ask_secret TOKEN "Paste the token (input hidden):"
  [[ -n "$TOKEN" ]] || { warn "nothing pasted"; exit 1; }
  token_is_valid "$TOKEN" || { warn "npm rejected that token (Bypass 2FA unticked? wrong account? trailing space?)"; exit 1; }
  printf '  %s✓%s accepted as %s\n' "$GREEN" "$RESET" "$EXPECTED_USER"
fi

# ── Stage 3: write the secret everywhere ──────────────────────────────────
stage "Set $SECRET_NAME"
say "Writing $SECRET_NAME to: $REPOS"
say "An existing $SECRET_NAME is replaced."
confirm "Go ahead?" || { say "Nothing changed."; exit 0; }
for repo in $REPOS; do set_repo_secret "$repo" "$TOKEN"; done

# ── Stage 4: confirm GitHub has it ────────────────────────────────────────
stage "Check"
for repo in $REPOS; do
  if gh secret list --repo "$repo" 2>/dev/null | grep -q "^$SECRET_NAME[[:space:]]"; then
    printf '  %s✓%s %s lists %s\n' "$GREEN" "$RESET" "$repo" "$SECRET_NAME"
  else
    warn "$repo does not list $SECRET_NAME"
  fi
done
say ""
note "GitHub only stores the secret; a workflow still has to use it to publish."
note "Whether the token may PUBLISH is only proven by a real publish."
pause "Done?"

finish
